export const PARENT_USER_LOGIN_REQUEST="PARENT_USER_LOGIN_REQUEST"
export const PARENT_USER_LOGIN_SUCCESS="PARENT_USER_LOGIN_SUCCESS"
export const PARENT_USER_LOGIN_FAIL="PARENT_USER_LOGIN_FAIL"
export const PARENT_USER_LOGOUT = "PARENT_USER_LOGOUT"

export const PARENT_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const PARENT_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const PARENT_REGISTER_FAIL="USER_REGISTER_FAIL"

export const PARENT_DETAILS_REQUEST="PARENT_DETAILS_REQUEST"
export const PARENT_DETAILS_SUCCESS="PARENT_DETAILS_SUCCESS"
export const PARENT_DETAILS_FAIL="PARENT_DETAILS_FAIL"
export const PARENT_DETAILS_RESET = "PARENT_DETAILS_RESET"


export const PARENTS_DETAILS_REQUEST = "PARENTS_DETAILS_REQUEST";
export const PARENTS_DETAILS_SUCCESS = "PARENTS_DETAILS_SUCCESS";
export const PARENTS_DETAILS_FAIL = "PARENTS_DETAILS_FAIL";
export const PARENTS_DETAILS_RESET = "PARENTS_DETAILS_RESET";

export const PARENT_DELETE_REQUEST = "PARENT_DELETE_REQUEST";
export const PARENT_DELETE_SUCCESS = "PARENT_DELETE_SUCCESS";
export const PARENT_DELETE_FAIL = "PARENT_DELETE_FAIL";
export const PARENT_DELETE_RESET = "PARENT_DELETE_RESET";

export const PARENT_UPDATE_REQUEST="PARENT_UPDATE_REQUEST"
export const PARENT_UPDATE_SUCCESS="PARENT_UPDATE_SUCCESS"
export const PARENT_UPDATE_FAIL="PARENT_UPDATE_FAIL"
export const PARENT_UPDATE_RESET = "PARENT_UPDATE_RESET"


export const CHILD_USER_LOGIN_REQUEST = "CHILD_USER_LOGIN_REQUEST";
export const CHILD_USER_LOGIN_SUCCESS = "CHILD_USER_LOGIN_SUCCESS";
export const CHILD_USER_LOGIN_FAIL = "CHILD_USER_LOGIN_FAIL";
export const CHILD_USER_LOGOUT = "CHILD_USER_LOGOUT";


export const CHILD_DETAILS_REQUEST = "CHILD_DETAILS_REQUEST";
export const CHILD_DETAILS_SUCCESS = "CHILD_DETAILS_SUCCESS";
export const CHILD_DETAILS_FAIL = "CHILD_DETAILS_FAIL";
export const CHILD_DETAILS_RESET = "CHILD_DETAILS_RESET";


export const CHILD_DELETE_REQUEST = "CHILD_DELETE_REQUEST";
export const CHILD_DELETE_SUCCESS = "CHILD_DELETE_SUCCESS";
export const CHILD_DELETE_FAIL = "CHILD_DELETE_FAIL";
export const CHILD_DELETE_RESET = "CHILD_DELETE_RESET";

export const CHILDREN_DETAILS_REQUEST = "CHILDREN_DETAILS_REQUEST";
export const CHILDREN_DETAILS_SUCCESS = "CHILDREN_DETAILS_SUCCESS";
export const CHILDREN_DETAILS_FAIL = "CHILDREN_DETAILS_FAIL";
export const CHILDREN_DETAILS_RESET = "CHILDREN_DETAILS_RESET";

export const CHILD_UPDATE_REQUEST = "CHILD_UPDATE_REQUEST";
export const CHILD_UPDATE_SUCCESS = "CHILD_UPDATE_SUCCESS";
export const CHILD_UPDATE_FAIL = "CHILD_UPDATE_FAIL";
export const CHILD_UPDATE_RESET = "CHILD_UPDATE_RESET";


export const STAFF_REGISTER_REQUEST = "STAFF_REGISTER_REQUEST";
export const STAFF_REGISTER_SUCCESS = "STAFF_REGISTER_SUCCESS";
export const STAFF_REGISTER_FAIL = "STAFF_REGISTER_FAIL";

export const STAFF_USER_LOGIN_REQUEST = "STAFF_USER_LOGIN_REQUEST";
export const STAFF_USER_LOGIN_SUCCESS = "STAFF_USER_LOGIN_SUCCESS";
export const STAFF_USER_LOGIN_FAIL = "STAFF_USER_LOGIN_FAIL";
export const STAFF_USER_LOGOUT = "STAFF_USER_LOGOUT";

export const STAFF_DETAILS_REQUEST = "STAFF_DETAILS_REQUEST";
export const STAFF_DETAILS_SUCCESS = "STAFF_DETAILS_SUCCESS";
export const STAFF_DETAILS_FAIL = "STAFF_DETAILS_FAIL";
export const STAFF_DETAILS_RESET = "STAFF_DETAILS_RESET";

export const STAFFS_DETAILS_REQUEST = "STAFFS_DETAILS_REQUEST";
export const STAFFS_DETAILS_SUCCESS = "STAFFS_DETAILS_SUCCESS";
export const STAFFS_DETAILS_FAIL = "STAFFS_DETAILS_FAIL";
export const STAFFS_DETAILS_RESET = "STAFFS_DETAILS_RESET";

export const STAFF_UPDATE_REQUEST = "STAFF_UPDATE_REQUEST";
export const STAFF_UPDATE_SUCCESS = "STAFF_UPDATE_SUCCESS";
export const STAFF_UPDATE_FAIL = "STAFF_UPDATE_FAIL";
export const STAFF_UPDATE_RESET = "STAFF_UPDATE_RESET";

export const STAFF_DELETE_REQUEST = "STAFF_DELETE_REQUEST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAIL = "STAFF_DELETE_FAIL";
export const STAFF_DELETE_RESET = "STAFF_DELETE_RESET";


export const ENROLLMENTS_DETAILS_REQUEST = "ENROLLMENTS_DETAILS_REQUEST";
export const ENROLLMENTS_DETAILS_SUCCESS = "ENROLLMENTS_DETAILS_SUCCESS";
export const ENROLLMENTS_DETAILS_FAIL = "ENROLLMENTS_DETAILS_FAIL";
export const ENROLLMENTS_DETAILS_RESET = "ENROLLMENTS_DETAILS_RESET";

export const ENROLLMENT_DETAILS_REQUEST = "ENROLLMENT_DETAILS_REQUEST";
export const ENROLLMENT_DETAILS_SUCCESS = "ENROLLMENT_DETAILS_SUCCESS";
export const ENROLLMENT_DETAILS_FAIL = "ENROLLMENT_DETAILS_FAIL";
export const ENROLLMENT_DETAILS_RESET = "ENROLLMENT_DETAILS_RESET";

export const ENROLLMENT_UPDATE_REQUEST = "ENROLLMENT_UPDATE_REQUEST";
export const ENROLLMENT_UPDATE_SUCCESS = "ENROLLMENT_UPDATE_SUCCESS";
export const ENROLLMENT_UPDATE_FAIL = "ENROLLMENT_UPDATE_FAIL";
export const ENROLLMENT_UPDATE_RESET = "ENROLLMENT_UPDATE_RESET";